name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.2.3

  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64, aarch64]
        include:
          - target: x86_64
            os: ubuntu-latest # Standard x86_64 runner
          - target: aarch64
            os: ubuntu-latest-arm64 # Specify an ARM64 runner (e.g., GitHub's ARM64 runner)
                                    # Note: The exact label for GitHub's ARM64 runners might change.
                                    # Please verify the current label from GitHub's documentation if needed.
    runs-on: ${{ matrix.os }} # Use the OS defined in the matrix strategy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka wheel
          # If your requirements.txt is for the application itself (not just build tools),
          # and Nuitka needs them during compilation (e.g., to find packages),
          # consider installing them here:
          # python -m pip install -r requirements.txt
          # Alternatively, ensure your build-bin.sh handles all necessary installations
          # within the target architecture's environment.

      - name: Determine Version
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "version=${VERSION}" >> $GITHUB_OUTPUT # Updated output method

      - name: Build Binary using build-bin.sh
        env:
          TARGET_ARCH_NAME: ${{ matrix.target }}
        run: |
          echo "Building for architecture: ${{ matrix.target }} on runner OS: ${{ matrix.os }}"
          chmod +x ./scripts/build-bin.sh
          ./scripts/build-bin.sh "${{ matrix.target }}" "${{ steps.get_version.outputs.version }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/bin/ublox_gnss_streamer_${{ matrix.target }}-${{ steps.get_version.outputs.version }}.tar.gz
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest # Release job can run on standard x86_64
    permissions:
      contents: write
    steps:
      - name: Checkout code (optional, if release notes are generated from repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version from Tag
        id: get_version_for_release
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT # Updated output method

      - name: Download AMD64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: binaries-x86_64
          path: downloaded-artifacts/x86_64

      - name: Download ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: binaries-aarch64
          path: downloaded-artifacts/aarch64

      - name: Display structure of downloaded files
        run: ls -R downloaded-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            downloaded-artifacts/x86_64/ublox_gnss_streamer_x86_64-${{ steps.get_version_for_release.outputs.version }}.tar.gz
            downloaded-artifacts/aarch64/ublox_gnss_streamer_aarch64-${{ steps.get_version_for_release.outputs.version }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

